import type { Metadata } from "next";
import localFont from "next/font/local";
import Provider from '@/redux/provider'
import { Setup } from "@/lib/actions";
import "./globals.css";

const poppinsRegular = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-poppins-regular",
  weight: "100 900",
});
const poppinsLight = localFont({
  src: "./fonts/Poppins-Light.ttf",
  variable: "--font-poppins-light",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Budget App",
  description: "Generated by create next app",
  icons: {
    icon: '/icons/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsRegular.variable} ${poppinsLight.variable} antialiased`}
      >
        <Provider>
          <Setup />
          {children}
        </Provider>
      </body>
    </html>
  );
}
